#!/bin/bash
# File              : colorschemes-changer
# License           : MIT
# Author            : Steven
# Date              : 30.07.2021
# Last Modified Date: 30.07.2021
# Last Modified By  : Steven
# colorschemes-changer
# Copyright (c) 2021 Steven Agustinus <steven87.ags@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


IMGDIR=$HOME/steven_data/mywallpaper/

function COLORCHANGER(){
 WALLPAPER="$(find "$IMGDIR"  -name "*.jpg" -or -name "*.png" | shuf -n1)"
 feh --randomize --bg-scale "$WALLPAPER";
 wal -i "$WALLPAPER" -n; 

}
COLORCHANGER
sleep 1

#special
background="$(grep background ~/.cache/wal/colors.yml | sed -e 's/"/ /g' | awk '{print $2}')" 
foreground="$(grep foreground ~/.cache/wal/colors.yml | sed -e 's/"/ /g' | awk '{print $2}')"
##Colors
color0="$(grep color0 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color1="$(grep color1: ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color2="$(grep color2 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color3="$(grep color3 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color4="$(grep color4 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color5="$(grep color5 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color6="$(grep color6 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color7="$(grep color7 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color8="$(grep color8 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color9="$(grep color9 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color10="$(grep color10 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color11="$(grep color11 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color12="$(grep color12 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color13="$(grep color13 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color14="$(grep color14 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"
color15="$(grep color15 ~/.cache/wal/colors.yml| sed -e 's/"/ /g' | awk '{print $2}')"

function XICON(){
sed -e "s/BGC/$background/g" \
    -e "s/FGC/$foreground/g" \
    -e "s/COLOR0/$color0/g" \
    -e "s/COLOR1/$color1/g" \
    -e "s/COLOR2/$color2/g" \
    -e "s/COLOR3/$color3/g" \
    -e "s/COLOR4/$color4/g" \
    -e "s/COLOR5/$color5/g" \
    -e "s/COLOR6/$color6/g" \
    -e "s/COLOR7/$color7/g" \
    -e "s/COLOR8/$color8/g" \
    -e "s/COLOR9/$color9/g" \
    -e "s/COLOR10/$color10/g" \
    -e "s/COLOR11/$color11/g" \
    -e "s/COLOR12/$color12/g" \
    -e "s/COLOR13/$color13/g" \
    -e "s/COLOR14/$color14/g" \
    -e "s/COLOR15/$color15/g" \
      ~/.config/xmobar/parameter-template/xmobarrc-parameter >  ~/.config/xmobar/xmobarrc

sed -e "s/BGC/$background/g" \
    -e "s/FGC/$foreground/g" \
    -e "s/COLOR0/$color0/g" \
    -e "s/COLOR1/$color1/g" \
    -e "s/COLOR2/$color2/g" \
    -e "s/COLOR3/$color3/g" \
    -e "s/COLOR4/$color4/g" \
    -e "s/COLOR5/$color5/g" \
    -e "s/COLOR6/$color6/g" \
    -e "s/COLOR7/$color7/g" \
    -e "s/COLOR8/$color8/g" \
    -e "s/COLOR9/$color9/g" \
    -e "s/COLOR10/$color10/g" \
    -e "s/COLOR11/$color11/g" \
    -e "s/COLOR12/$color12/g" \
    -e "s/COLOR13/$color13/g" \
    -e "s/COLOR14/$color14/g" \
    -e "s/COLOR15/$color15/g" \
      ~/.config/xmobar/parameter-template/xmobarrc2-parameter >  ~/.config/xmobar/xmobarrc2
}

XICON
xmonad --restart
